name: CI and GitOps Trigger

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ayush12141
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ayush12141/pipecd-demo:${{ github.sha }}

      - name: Update Config Repo Tag
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "ayushmore1214@gmail.com"
          git config --global user.name "Ayush More"
          
          # Clone the Config Repo
          git clone https://x-access-token:${GH_PAT}@github.com/Ayushmore1214/pipecd-gitops-config.git
          cd pipecd-gitops-config
          
          # Update the image tag in the K8s manifest
          # (Assumes your deployment is in kubernetes/base/deployment.yaml)
          sed -i "s|image: ayush12141/pipecd-demo:.*|image: ayush12141/pipecd-demo:${{ github.sha }}|g" kubernetes/base/deployment.yaml
          
          git add .
          git commit -m "feat: update image tag to ${{ github.sha }} [skip ci]"
          git push